name: esp32cam_app
description: ESP32-CAM 监控 App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  # WebView 用于显示 MJPEG 流
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.14.0

  # 保持屏幕常亮
  wakelock_plus: ^1.2.5

  # Cupertino 图标
  cupertino_icons: ^1.0.2

  shared_preferences: ^2.2.2
  flutter_mjpeg: ^2.0.4
  multicast_dns: ^0.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "1740671459962.jpg.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true